// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp9f2oJUSGkWWkjlSndhrr5ed3ITnuydE',
    appId: '1:172559321044:web:f9f64bbb50a626b2c83841',
    messagingSenderId: '172559321044',
    projectId: 'quickbite-6f892',
    authDomain: 'quickbite-6f892.firebaseapp.com',
    storageBucket: 'quickbite-6f892.firebasestorage.app',
    measurementId: 'G-L4NVN8KCS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS3quk5sceOOOPM4R2wk7mj_mXNAHLicU',
    appId: '1:172559321044:android:9010e9b1463eca18c83841',
    messagingSenderId: '172559321044',
    projectId: 'quickbite-6f892',
    storageBucket: 'quickbite-6f892.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmBwr2Sz4PGd3idnAbqABPvnNq282uPmI',
    appId: '1:172559321044:ios:3250026bf7a3c490c83841',
    messagingSenderId: '172559321044',
    projectId: 'quickbite-6f892',
    storageBucket: 'quickbite-6f892.firebasestorage.app',
    iosBundleId: 'com.example.quickbite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmBwr2Sz4PGd3idnAbqABPvnNq282uPmI',
    appId: '1:172559321044:ios:3250026bf7a3c490c83841',
    messagingSenderId: '172559321044',
    projectId: 'quickbite-6f892',
    storageBucket: 'quickbite-6f892.firebasestorage.app',
    iosBundleId: 'com.example.quickbite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp9f2oJUSGkWWkjlSndhrr5ed3ITnuydE',
    appId: '1:172559321044:web:e81bc688825f097ac83841',
    messagingSenderId: '172559321044',
    projectId: 'quickbite-6f892',
    authDomain: 'quickbite-6f892.firebaseapp.com',
    storageBucket: 'quickbite-6f892.firebasestorage.app',
    measurementId: 'G-4WSMZFPYKN',
  );

}